modLoader="javafml"
loaderVersion="[36,)"
license="MIT Liscence"

[[mods]]
modId="machina"
version="${file.jarVersion}"
displayName="Machina"
displayURL="https://github.com/Cy4Shot/MACHINA"
logoFile="logo.png"
credits="Thank you to everyone in Cy4's Modding Community :D"
authors="The Machina Team and Cy4's community"
description='''
MACHINA is a mod about tech and space exploration.
'''

[[dependencies.machina]]
    modId="fancyvideo-api"
    mandatory=true
    ordering="AFTER"
    side="BOTH"

[[dependencies.machina]]
    modId="geckolib3"
    mandatory=true
    versionRange="[3.0.54,)"
    ordering="BEFORE"
    side="BOTH"

[[dependencies.machina]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.machina]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
