modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="machina"
version="0.1.0"
displayName="MACHINA"
authors="Cy4"
description='''A sci-fi tech exploration mod.'''

[[dependencies.machina]]
    modId="forge"
    mandatory=true
    versionRange="[47.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.machina]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"