package com.machina.api.starchart.name;

public class SystemNameGenerator extends NameGenerator {

	@Override
	public String getNames() {
		return "Aelion Arcturus Baelon Belara Caelum Cygnus Daelus Eos Etherea Faelon Galatia Helion Hydra Icarus Isilon Jaelon Kalira Kepler Lyra Maelstrom Merope Naelus Nebula Nymeria Orionis Pax Phyra Quinlan Quorra Raelion Saphira Selene Solara Tiberia Valara Vega Vesper Zendar Astraeus Bravura Celestia Delphine Erebus Feronia Galadriel Halcyon Ilios Jovian Kaelis Lycoris Mira Neoma Oberon Phaedra Quasar Rhea Serenos Talara Vespera Zylara Zenith Aerilon Alara Belisarius Callisto Daeron Elara Faros Gaius Helia Isara Jaxira Kalidon Leilon Maris Nyx Orin Persei Quinara Reyna Solaris Tranquil Vaelon Zephyr Asteria Borealis Caelestis Daedalus Elyria Faranth Garion Haedra Ilyria Janara Kaelon Leandros Mistral Norath Orithia Paxara Quirinus Rilanth Selara Solstice Tenebris Valtor Veloria Zephyrus Arion Baelith Chara Davos Elion Fenix Gavriel Halora Inara Jareth Kaerith Leorion Meridian Nyra Orionna Phenex Qorath Rialto Seladon Starion Thalassa Valeria Vesperion Zenithar Amara Balerion Calypsa Delara Elionis Faelan Galen Helara Inarael Jaxor Kaelith Lenara Meridia Neral Orionis Phaedros Qyra Rilan Seraphis Talaris Valeska Velion Zethra Aristea Belisar Celeron Dione Elondra Farin Gavros Halcyra Illyon Janaris Kaelonith Leoros Meira Norion Orithra Pheron Quellan Rialos Selendis Stellara Thalor Valion Vespera Zephyrion Aelionis Bellara Calyron Davros Elorin Feron Gaelan Halios Inareth Jaxiris Kaeloria Lenith Meridiael Nythra Orionis Phaedon Qyron Rialth Selantha Solaris Taranis Valoris Velanor Zythra Andara Baelonith Charis Daelion Elos Fenara Galenor Halith Inorael Jarethia Kaeloran Leosar Merithon Nyria Orionnael Pheronix Qorathis Rilanis Selith Solarael Tenebrisar Valoria Velorath Zetheria Anaris Belaron Calysta Daviros Eloria Fariel Galenth Haloris Ilyonel Janarith Kaeloriae Leonth Merithos Nythoria Orionth Phaedral Qyros Rialtha Selenis Stellaris Thalaris Valonor Vesperion Zylarael Aelionar Bellaris Caeloria Davorith Elorian Faris Gavrelios Halionis Inoraeth Jarethis Kaelorith Leonith Meriel Norionis Orithrael Pheronia Qylar Rialor Seleron Solarith Talarael Valarian Velorin Zephyrith Aeronith Baelar Celara Delion Elorith Faeloria Galeth Halionis Ilyoris Janarion Kaeloris Leonthos Merionith Nythara Oriontha Phaedran Qylaris Rialosel Selion Solaraeth Tenebrisel Valonora Veloris Zylor Aelorith Bellion Caelorith Davionis Elorineth Farion Galenith Halior Inoraion Jarethos Kaeloritha Leonar Merithara Nythion Orionisar Pheronith Qylaron Rialthos Selithar Stellaran Thalaron Valorian Velora Zethera"
				+ "Zarathra Vexilon Drakkor Seriphos Jandara Klystarn Avorax Lyqros Zelphar Mintrax Vorlon Nexara Krythos Orphid Klystron Xanthis Velmor Rithion Skolar Nexdria Jorvex Xytrion Korthis Veldran Pyrion Zilthar Nympha Trelion Xyndrax Vortexia Orithos Jykron Valthor Zarnak Xylos Drathir Xyphos Krelthar Pyrithos Zenthia Myrion Sylphos Vrothar Ylthos Kryndor Tormax Xylaren Zathros Meltron Grithar Zyndor Naxalon Vylaris Tyrion Krythar Xandar Thrylos Xynthor Jorthan Zylithor Dragnar Xylithra Klyndor Vylos Pyrithar Nexon Jorax Xaldria Qytheria Mython Veldros Zykros Sylthar Varnathor Xymthos Krylor Andrax Jykthar Nylothor Xylanthra Vynkros Torlax Zyphron Velthros Dranthia Xyphros Klythion Pyntheria Qylaros Jorthis Zandrithor Krythor Voraxis Xylanthos Zynthar Melkros Vykthor Draknor Xylithor Varnothra Krynthos Tyrionis Zylos Vylathor Pyrithia Zormar Xynthara Qylax Kryndros Myrikor Zynthros Varlon Xylaros Drathos Zylothar Melthron Zyndros Vornoth Xykran Pylothra Krymthos Varkon Zylor Drathan Qyndros Klytheria Vexor Tormithos Xyldon Nythron Zarmith Pyrithon Myrithar Zythor Qyrithia Klyndros Varkothor Velkros Jykthor Klymthos Xylathor Drathria Zormithon Pylothor Krythorium Vykron Melthos Jorathia Zynthor Pyrathos Klythos Xylathra Tormithar Qyrax Krymor Zythria Nythos Varkos Drathor Xykrath Varnithos Jykthar Pylothos Vylathra Krynor Tormithra Zornithon Pyrathia Klythar Xylosian Zyntharia Varnithra Qyntheria Melkron Drathria Pylathar Zormith Krython Varnithos Xykran Tormothor Jorathos Klymthar Vylathos Zynthra Nythoria Qyrithar Drathos Pyrithra Xylothor Krynthra Zormath Klythron Pylathos Vykthar Tormithos Krymthor Melthra Zyntheria Jorathor Varnithar Xykrath Klymthor Pylithor Vexarian Zornithar Drathar Krython Varnithra Qylaron Melthos Xyldron Jorathra Zynthrian Pyrithar Klythria Zormar Vornithar Tormithia Krymthar Jykthos Varkoth Xylanthros Pylithra Drathria Nythorian Qynthera Melkros Zynthian Klythron Vykthos Pyrithon Varnithos Jorathra Zormithra Xylor Kryndros Klythar Pylithos Vykthon Tormithar Drathos Jykthar Zynthra Krynthos Varnithia Qylaros Klymthos Xylanthra Nythar Pyrithos Zylothra Dranthos Zormithos Krython Varnithria Tormithos Jykthor Melthar Qyntheria"
				+ "StarLace Arkastra Velosian Orbithia Taphaia Thalia Taphaia Aurora Dimisys Galilea Braheluna Lippertopia Janssara Harriota Aegira Amaterra Dagonia Tadmorion Meztila Smertria Hypatiaa Quijotia Dulcinean Rocinantia Sanchoria Thestias Saffara Samhara Majritia Fortispace Draugria Poltara Phobeta Arbera Tassilis Madrial Naqalya Bocaprime Yanya Sissara Ganjara Tondrae Eburon Drukylos Yvaga Naronia Guaranis Mastikara Bendidian Nakanbella Awasisa Caleuchea Wangshia Melquidian Pipitean Ditsolian Asyelea Velesia Finlune Onasilo Surtis Boinaya Eyekea Cayahuanca Hämarika Abolos Hiisia Bélisamar Mintomian Neris Togea Iolaus Koyopa' Indépendia Ixbalana Victoriapeach Magoria Foldara Santamasa Noifasi Kaviania Babylonis Branal Alefia Letea Churae Wadirun Burune Stabura Beiruton Umbaessia Vyti Peitrussa";
	}

	@Override
	public int getLength() {
		return 3;
	}

	@Override
	public int getMinLength() {
		return 1;
	}
}